### ISSUE TITLE
Navigation bar has large title doesn't work correctly

### ISSUE THREAD

**Issue by ribilynn** [timbersoftware/SwiftUI-Introspect#2]
After setting tableView's separator to none, the navigation bar becomes transparent and won't react during scrolling such as shrinking, changing color.
Guess changing tableView's property will destroy the scroll delegate somehow.

**Comment by ldiqual** [comment]
This is interesting. There's not much magic going on other than accessing whatever table view is in the hierarchy, and I don't know why it would have this behavior. Will try to reproduce on my end and investigate. In the meantime, if you have an example project, would you mind sending it our way? Thank you!

**Comment by ribilynn** [comment]
Found the problem only occurs when the navigation bar displays a large title.
Just create a new SwiftUI project and use this can reproduce it.


    struct ContentView: View {
        var body: some View {
            NavigationView {
                List(0...10, id: \.self) { num in
                    Text(String(num))
                }
                .navigationBarTitle("Title", displayMode: .large)
                .introspectTableView { tableView in
                    tableView.separatorStyle = .none
                }
            }
        }
    }

**Comment by ldiqual** [comment]
Thanks a lot! I can reproduce on my end, I'll see if I can find a workaround.

**Comment by ldiqual** [comment]
Fyi `List { ... }.background(Text("Some text"))` causes the same bug.

**Comment by ribilynn** [comment]
You're right. Adding a background to `List` or `ScrollView` embedded in `NavigationView` will cause the same bug. Seems that it affects the scroll delegate inside. Just SwiftUI's problem.
Thank you for investigation!

**Comment by ldiqual** [comment]
Fixed in ec46ea4 by using `.overlay` instead of `.background`. Will release 0.0.3 soon.

**Comment by ldiqual** [comment]
0.0.3 is now available as a tag for SwiftPM and in the Cocoapods trunk. Let me know if it works for you!

**Comment by ribilynn** [comment]
Well...No😅In the same code above, after updating, method `.introspectTableView` doesn't work at all. separator still appears.
And I found a workaround. Call `.instrospect...` method by the view that embedded in `List`, instead of by the `List` itself. Any view in `List` or add a `Spacer().introspect...` is OK. In this way, Both `.background` and `.overlay` works well.

**Comment by ldiqual** [comment]
Oh boy, I didn't even notice. Even the tests didn't pass. Fixing.

**Comment by ldiqual** [comment]
This is now fixed in 0.0.4 using `previousSibling` instead of `nextSibling`.
